'use client'

import React from 'react'

interface Insight {
  id: string
  category: 'performance' | 'capacity' | 'quality' | 'trend'
  text: string
  confidence: number
  dataPoints: string[]
}

interface AutoGeneratedInsightsProps {
  insights: Insight[]
  className?: string
}

/**
 * Auto-Generated Insights - AI-powered commentary on network metrics
 * Generates human-readable insights from complex data patterns
 */
export default function AutoGeneratedInsights({
  insights,
  className = ''
}: AutoGeneratedInsightsProps) {
  const getCategoryIcon = (category: Insight['category']) => {
    switch (category) {
      case 'performance': return '⚡'
      case 'capacity': return '📊'
      case 'quality': return '⭐'
      case 'trend': return '📈'
    }
  }

  const getCategoryLabel = (category: Insight['category']) => {
    switch (category) {
      case 'performance': return 'Performance'
      case 'capacity': return 'Capacité'
      case 'quality': return 'Qualité'
      case 'trend': return 'Tendance'
    }
  }

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 0.8) return 'text-green-400'
    if (confidence >= 0.6) return 'text-yellow-400'
    return 'text-orange-400'
  }

  return (
    <div className={`bg-slate-800/20 border border-white/5 rounded-2xl p-6 ${className}`}>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-black text-white uppercase flex items-center gap-2">
          <span className="text-lg">💬</span> Insights Automatiques
        </h3>
        <div className="text-xs text-slate-400">
          {insights.length} observation{insights.length > 1 ? 's' : ''}
        </div>
      </div>

      {insights.length === 0 ? (
        <p className="text-center text-slate-400 py-8 text-sm">
          En attente d'analyses...
        </p>
      ) : (
        <div className="space-y-4">
          {insights.map((insight) => {
            const icon = getCategoryIcon(insight.category)
            const label = getCategoryLabel(insight.category)
            const confidenceColor = getConfidenceColor(insight.confidence)

            return (
              <div
                key={insight.id}
                className="bg-slate-900/50 border border-white/10 rounded-xl p-4 hover:bg-slate-900/70 hover:border-white/20 transition-all duration-200 shadow-lg"
              >
                {/* Header */}
                <div className="flex items-start gap-3 mb-3">
                  <span className="text-2xl">{icon}</span>
                  <div className="flex-1">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs font-bold text-blue-400 uppercase">
                        {label}
                      </span>
                      <div className="flex items-center gap-1">
                        <span className="text-xs text-slate-500">Confiance:</span>
                        <span className={`text-xs font-bold ${confidenceColor}`}>
                          {(insight.confidence * 100).toFixed(0)}%
                        </span>
                      </div>
                    </div>
                    
                    {/* Insight text */}
                    <p className="text-sm text-white leading-relaxed">
                      {insight.text}
                    </p>
                  </div>
                </div>

                {/* Data points */}
                {insight.dataPoints.length > 0 && (
                  <div className="ml-11 pt-3 border-t border-white/5">
                    <p className="text-xs text-slate-500 mb-2">Basé sur:</p>
                    <div className="flex flex-wrap gap-2">
                      {insight.dataPoints.map((point, idx) => (
                        <span
                          key={idx}
                          className="px-2 py-1 rounded bg-slate-950/50 border border-white/10 text-xs text-slate-400"
                        >
                          {point}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
