'use client'

import React, { useMemo } from 'react'
import { useTopCells, useAlerts, useNetworkStats } from '@/lib/hooks'
import { useCongestion } from '@/lib/hooks/useCongestion'
import { DEFAULT_HOUR_ISO } from '@/lib/time'
import CongestionMap from '@/components/dashboard/CongestionMap'
import CongestionPreviewCard from '@/components/dashboard/CongestionPreviewCard'
import Link from 'next/link'
import { useRole } from '@/lib/role-context'
import { UserRole } from '@/lib/types'
import ExecutiveKpiCard from '@/components/dashboard/ExecutiveKpiCard'
import AttentionPoints from '@/components/dashboard/AttentionPoints'
import CriticalAlertBanner from '@/components/dashboard/CriticalAlertBanner'
import FullScreenToggle from '@/components/dashboard/FullScreenToggle'
import IncidentPanel from '@/components/dashboard/IncidentPanel'
import AlertTimeline from '@/components/dashboard/AlertTimeline'
import { generateMockTimeSeries } from '@/lib/hooks/useTimeSeries'
import { AlertBadge, DateRangePicker, GaugeChart, KpiCard } from '@/components/ui'
import SmallMultiplesChart from '@/components/dashboard/SmallMultiplesChart'
import LoadDistributionHistogram from '@/components/dashboard/LoadDistributionHistogram'
import CalendarHeatmap from '@/components/dashboard/CalendarHeatmap'
import IntelligentRecommendations from '@/components/dashboard/IntelligentRecommendations'
import ExecutiveSummaryCards from '@/components/dashboard/ExecutiveSummaryCards'
import AutoGeneratedInsights from '@/components/dashboard/AutoGeneratedInsights'
import PeriodComparator from '@/components/dashboard/PeriodComparator'
import SlaGauges from '@/components/dashboard/SlaGauges'
import ActionItems from '@/components/dashboard/ActionItems'
import ExportButton from '@/components/dashboard/ExportButton'
import CellSelector from '@/components/dashboard/CellSelector'
import CorrelationChart from '@/components/dashboard/CorrelationChart'
import TechnicalCellsTable from '@/components/dashboard/TechnicalCellsTable'
import ServiceHealthIndicator from '@/components/dashboard/ServiceHealthIndicator'
import SystemSparkline from '@/components/dashboard/SystemSparkline'
import FilteredLogStream from '@/components/dashboard/FilteredLogStream'

// Component visibility matrix based on roles
const componentVisibility: Record<UserRole, Record<string, boolean>> = {
  director: {
    kpiCards: true,
    interactiveMap: false,
    timeseries: true,
    alertsList: true,
    cellsTable: false,
    logsIncidents: false,
    recommendations: false,
    exportReporting: true
  },
  network_engineer: {
    kpiCards: true,
    interactiveMap: true,
    timeseries: true,
    alertsList: true,
    cellsTable: true,
    logsIncidents: false,
    recommendations: false,
    exportReporting: false
  },
  sys_admin: {
    kpiCards: true,
    interactiveMap: false,
    timeseries: true,
    alertsList: true,
    cellsTable: false,
    logsIncidents: true,
    recommendations: false,
    exportReporting: false
  },
  network_operator: {
    kpiCards: true,
    interactiveMap: true,
    timeseries: true,
    alertsList: true,
    cellsTable: true,
    logsIncidents: false,
    recommendations: false,
    exportReporting: false
  },
  performance_engineer: {
    kpiCards: false,
    interactiveMap: true,
    timeseries: true,
    alertsList: true,
    cellsTable: true,
    logsIncidents: false,
    recommendations: true,
    exportReporting: true
  },
  operations_manager: {
    kpiCards: true,
    interactiveMap: true,
    timeseries: true,
    alertsList: true,
    cellsTable: false,
    logsIncidents: false,
    recommendations: true,
    exportReporting: true
  }
}

const canView = (role: UserRole, component: string): boolean => {
  return componentVisibility[role]?.[component] ?? false
}

interface DashboardByRoleProps {
  role?: UserRole
}

export default function DashboardByRole({ role: propRole }: DashboardByRoleProps = {}) {
  const { role: contextRole } = useRole()
  const role = propRole || contextRole
  const { data: topCells } = useTopCells(DEFAULT_HOUR_ISO, 10)
  const { data: alerts } = useAlerts()
  const { data: stats } = useNetworkStats()
  const { data: congestionCells } = useCongestion(DEFAULT_HOUR_ISO, 70, 90)

  const metrics = useMemo(() => {
    if (!topCells || topCells.length === 0) return null
    const peak = topCells[0]
    const avg = topCells.reduce((sum, c) => sum + c.totalActivity, 0) / topCells.length
    const totalData = topCells.reduce((sum, c) => sum + c.totalInternet, 0)

    return {
      peakValue: peak.totalActivity.toFixed(1),
      peakId: peak.cellId,
      avgLoad: avg.toFixed(1),
      dataVolume: (totalData / 1024).toFixed(2),
      activeNodes: stats?.totalCells || topCells.length * 12
    }
  }, [topCells, stats])

  const congestionMetrics = useMemo(() => {
    if (!congestionCells || congestionCells.length === 0) {
      return { critical: 0, warning: 0, healthScore: 100 }
    }
    const critical = congestionCells.filter(c => c.score >= 90).length
    const warning = congestionCells.filter(c => c.score >= 70 && c.score < 90).length
    const avgScore = congestionCells.reduce((acc, c) => acc + c.score, 0) / congestionCells.length
    const healthScore = Math.max(0, 100 - avgScore)
    
    return { critical, warning, healthScore }
  }, [congestionCells])

  // DIRECTOR VIEW - Executive Dashboard
  if (role === 'director') {
    // Generate mock sparkline data (in real app, fetch from API)
    const healthSparkline = generateMockTimeSeries(7, 85, 10).map(d => d.value)
    const cellsSparkline = generateMockTimeSeries(7, stats?.totalCells || 100, 10).map(d => d.value)
    const alertsSparkline = generateMockTimeSeries(7, congestionMetrics.critical + congestionMetrics.warning, 5).map(d => d.value)
    
    // Mock satisfaction score (in real app, calculate from call success rate)
    const satisfactionScore = 96
    
    // Generate attention points from alerts
    const attentionPoints = [
      ...(congestionMetrics.critical > 0 ? [{
        id: 1,
        title: `${congestionMetrics.critical} zones critiques détectées`,
        severity: 'critical' as const,
        description: 'Intervention immédiate requise pour éviter dégradation service'
      }] : []),
      ...(congestionMetrics.warning > 0 ? [{
        id: 2,
        title: `${congestionMetrics.warning} zones en alerte`,
        severity: 'warning' as const,
        description: 'Surveillance accrue recommandée'
      }] : []),
      ...(alerts && alerts.length > 5 ? [{
        id: 3,
        title: `${alerts.length} alertes actives`,
        severity: 'info' as const,
        description: 'Volume d\'alertes supérieur à la normale'
      }] : [])
    ]

    return (
      <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
        {/* Executive KPIs with Sparklines */}
        {canView(role, 'kpiCards') && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <ExecutiveKpiCard
            title="Santé Réseau"
            value={congestionMetrics.healthScore.toFixed(0)}
            unit="%"
            trend={-3.2}
            trendLabel="vs hier"
            sparklineData={healthSparkline}
            color="green"
            icon="💚"
          />
          
          <ExecutiveKpiCard
            title="Cellules Actives"
            value={stats?.totalCells || 0}
            unit="nœuds"
            trend={1.5}
            trendLabel="vs hier"
            sparklineData={cellsSparkline}
            color="blue"
            icon="📡"
          />
          
          <ExecutiveKpiCard
            title="Alertes Actives"
            value={congestionMetrics.critical + congestionMetrics.warning}
            unit="incidents"
            trend={-12}
            trendLabel="vs hier"
            sparklineData={alertsSparkline}
            color={congestionMetrics.critical > 0 ? 'red' : 'yellow'}
            icon={congestionMetrics.critical > 0 ? '🚨' : '⚠️'}
          />
        </div>
        )}

        {/* Satisfaction & Attention Points Row */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Satisfaction Gauge */}
          <div className="bg-gradient-to-br from-purple-900/20 to-purple-900/5 border border-purple-500/20 rounded-2xl p-6 flex flex-col items-center justify-center">
            <h3 className="text-xs text-slate-400 uppercase font-bold mb-4 w-full">
              Satisfaction Client
            </h3>
            <GaugeChart
              value={satisfactionScore}
              max={100}
              size={140}
              label="Score Global"
              thresholds={[
                { value: 90, color: '#10b981' },
                { value: 70, color: '#eab308' },
                { value: 0, color: '#ef4444' }
              ]}
            />
            <div className="mt-4 text-center">
              <p className="text-xs text-slate-500">Basé sur</p>
              <p className="text-sm font-bold text-purple-400">
                {((stats?.totalCells || 100) * 1000).toLocaleString()} appels
              </p>
            </div>
          </div>

          {/* Attention Points */}
          <div className="lg:col-span-2">
            <AttentionPoints
              points={attentionPoints}
              maxItems={3}
            />
          </div>
        </div>

        {/* Alert Banner */}
        {(congestionMetrics.critical > 0 || congestionMetrics.warning > 0) && (
          <div className="bg-gradient-to-r from-red-900/30 to-orange-900/30 border border-red-500/40 rounded-2xl p-6 backdrop-blur-sm">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="text-3xl">⚠️</div>
                <div>
                  <h3 className="text-lg font-black text-white">Intervention Requise</h3>
                  <p className="text-sm text-slate-200 mt-1">
                    {congestionMetrics.critical} zones en état critique nécessitent attention
                  </p>
                </div>
              </div>
              <Link href="/dashboard/congestion">
                <button className="px-8 py-3 bg-red-600 hover:bg-red-700 text-white rounded-xl font-bold text-sm uppercase tracking-wider transition-all">
                  Accéder à l'Analyse
                </button>
              </Link>
            </div>
          </div>
        )}

        {/* Simple Map View - Hidden for Director */}
        {canView(role, 'interactiveMap') && (
        <div className="relative bg-slate-900/50 backdrop-blur-sm border border-white/5 rounded-2xl overflow-hidden shadow-xl min-h-[500px]">
          <CongestionMap
            congestionCells={congestionCells || []}
            warnThreshold={70}
            critThreshold={90}
            className="w-full h-full"
          />
        </div>
        )}

        {/* Quick Links */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <Link href="/dashboard/congestion">
            <div className="p-4 bg-slate-800/50 border border-white/5 rounded-xl hover:border-blue-500/30 transition-all cursor-pointer text-center">
              <p className="text-2xl mb-2">📊</p>
              <p className="text-xs font-bold text-slate-300">Congestion</p>
            </div>
          </Link>
          <Link href="/dashboard/alerts">
            <div className="p-4 bg-slate-800/50 border border-white/5 rounded-xl hover:border-red-500/30 transition-all cursor-pointer text-center">
              <p className="text-2xl mb-2">🚨</p>
              <p className="text-xs font-bold text-slate-300">Alertes</p>
            </div>
          </Link>
          {canView(role, 'cellsTable') && (
          <Link href="/dashboard/cells">
            <div className="p-4 bg-slate-800/50 border border-white/5 rounded-xl hover:border-green-500/30 transition-all cursor-pointer text-center">
              <p className="text-2xl mb-2">📡</p>
              <p className="text-xs font-bold text-slate-300">Cellules</p>
            </div>
          </Link>
          )}
          <Link href="/dashboard/heatmap">
            <div className="p-4 bg-slate-800/50 border border-white/5 rounded-xl hover:border-yellow-500/30 transition-all cursor-pointer text-center">
              <p className="text-2xl mb-2">🔥</p>
              <p className="text-xs font-bold text-slate-300">Heatmap</p>
            </div>
          </Link>
        </div>
      </div>
    )
  }

  // NETWORK ENGINEER VIEW - Technical Dashboard
  if (role === 'network_engineer') {
    // Prepare data for Cell Selector
    const [selectedCells, setSelectedCells] = React.useState<string[]>([])
    const cellSelectorData = topCells?.map(cell => ({
      id: cell.cellId,
      name: `Cell ${cell.cellId}`,
      zone: 'Lombardy', // In real app, fetch from API
      load: cell.totalActivity
    })) || []

    // Prepare correlation data
    const correlationData = topCells?.map(cell => ({
      x: cell.totalActivity, // Load %
      y: Math.floor(cell.totalActivity * 100 + Math.random() * 200), // Mock users count
      cellId: cell.cellId,
      label: `Cell ${cell.cellId}`
    })) || []

    // Prepare technical table data
    const technicalCells = topCells?.map(cell => ({
      cellId: cell.cellId,
      zone: 'Lombardy',
      rsrp: -85 + Math.random() * 30, // Mock RSRP
      sinr: 10 + Math.random() * 20, // Mock SINR
      throughput: cell.totalInternet / 1000, // Convert to Mbps
      load: cell.totalActivity,
      users: Math.floor(cell.totalActivity * 10),
      status: (
        cell.totalActivity >= 90 ? 'critical' :
        cell.totalActivity >= 70 ? 'warning' :
        'good'
      ) as 'good' | 'warning' | 'critical'
    })) || []

    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
        {/* Header */}
        <div>
          <h2 className="text-2xl font-black text-white">Network Engineering</h2>
          <p className="text-sm text-slate-400 mt-1">Analyse technique RF et optimisation</p>
        </div>

        {/* Cell Selector */}
        <CellSelector
          cells={cellSelectorData}
          selectedCells={selectedCells}
          onChange={setSelectedCells}
          maxSelection={5}
        />

        {/* Technical KPIs */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <KpiCard
            title="Charge Réseau Max"
            value={metrics?.peakValue || '0.0'}
            trend={`Nœud ${metrics?.peakId}`}
            color="red"
          />
          <KpiCard
            title="Charge Moyenne"
            value={metrics?.avgLoad || '0.0'}
            trend="Erlang/MHz"
            color="blue"
          />
          <KpiCard
            title="Débit Données"
            value={metrics?.dataVolume || '0.0'}
            trend="Gb/Hour"
            color="green"
          />
          <KpiCard
            title="Score NCI"
            value={congestionMetrics.healthScore.toFixed(1)}
            trend="Network Congestion Index"
            color={congestionMetrics.critical > 0 ? 'red' : 'green'}
          />
        </div>

        {/* Correlation Chart */}
        <CorrelationChart
          data={correlationData}
          xLabel="Charge (%)"
          yLabel="Nombre d'utilisateurs"
          onPointClick={(cellId) => {
            console.log('Cell clicked:', cellId)
          }}
        />

        {/* Map + Metrics */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Map */}
          <div className="lg:col-span-2 relative bg-slate-900/50 backdrop-blur-sm border border-white/5 rounded-2xl overflow-hidden shadow-xl min-h-[500px]">
            <CongestionMap
              congestionCells={congestionCells || []}
              warnThreshold={70}
              critThreshold={90}
              className="w-full h-full"
            />
          </div>

          {/* Quick Metrics */}
          <div className="space-y-6">
            <div className="bg-slate-800/20 border border-white/5 rounded-2xl p-5">
              <h3 className="text-xs font-black text-slate-400 uppercase mb-4">Métriques Rapides</h3>
              <div className="space-y-3 text-xs">
                <div className="flex justify-between">
                  <span className="text-slate-400">Cellules Actives</span>
                  <span className="font-bold text-green-400">{stats?.totalCells || 0}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Charge Moyenne</span>
                  <span className="font-bold text-blue-400">{metrics?.avgLoad || '0'} E</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Alertes Actives</span>
                  <span className={`font-bold ${alerts?.length ? 'text-red-400' : 'text-green-400'}`}>
                    {alerts?.length || 0}
                  </span>
                </div>
              </div>
            </div>

            <div className="bg-slate-800/20 border border-white/5 rounded-2xl p-5">
              <h3 className="text-xs font-black text-slate-400 uppercase mb-4">Statut Zones</h3>
              <div className="grid grid-cols-2 gap-2">
                <div className="p-2 bg-red-900/20 border border-red-500/20 rounded text-center">
                  <p className="text-xs text-slate-400">Critique</p>
                  <p className="text-lg font-black text-red-500">{congestionMetrics.critical}</p>
                </div>
                <div className="p-2 bg-yellow-900/20 border border-yellow-500/20 rounded text-center">
                  <p className="text-xs text-slate-400">Alerte</p>
                  <p className="text-lg font-black text-yellow-500">{congestionMetrics.warning}</p>
                </div>
              </div>
            </div>

            <CongestionPreviewCard />
          </div>
        </div>

        {/* Technical Cells Table */}
        <TechnicalCellsTable
          cells={technicalCells}
          onCellClick={(cellId) => {
            console.log('View cell details:', cellId)
          }}
        />
      </div>
    )
  }

  // SYS ADMIN VIEW - Operational Dashboard
  if (role === 'sys_admin') {
    // Generate mock services data
    const services = [
      {
        name: 'API Gateway',
        status: 'healthy' as const,
        uptime: 99.9,
        responseTime: 45,
        lastCheck: new Date(),
        icon: '🌐'
      },
      {
        name: 'Database',
        status: 'healthy' as const,
        uptime: 99.8,
        responseTime: 12,
        lastCheck: new Date(),
        icon: '💾'
      },
      {
        name: 'Keycloak',
        status: congestionMetrics.critical > 0 ? 'degraded' as const : 'healthy' as const,
        uptime: 99.5,
        responseTime: 156,
        lastCheck: new Date(),
        icon: '🔐'
      },
      {
        name: 'Redis Cache',
        status: 'healthy' as const,
        uptime: 100,
        responseTime: 3,
        lastCheck: new Date(),
        icon: '⚡'
      },
      {
        name: 'Message Queue',
        status: 'healthy' as const,
        uptime: 99.7,
        responseTime: 8,
        lastCheck: new Date(),
        icon: '📬'
      },
      {
        name: 'Storage Service',
        status: 'healthy' as const,
        uptime: 99.9,
        responseTime: 67,
        lastCheck: new Date(),
        icon: '📦'
      }
    ]

    // Generate mock CPU/Memory data
    const cpuData = Array.from({ length: 50 }, (_, i) => 55 + Math.sin(i / 5) * 15 + Math.random() * 10)
    const memoryData = Array.from({ length: 50 }, (_, i) => 48 + Math.cos(i / 7) * 12 + Math.random() * 8)

    // Generate mock logs
    const mockLogs = [
      {
        id: '1',
        timestamp: new Date(Date.now() - 5 * 60000),
        level: 'ERROR' as const,
        message: 'Database connection timeout after 30s',
        source: 'db-service'
      },
      {
        id: '2',
        timestamp: new Date(Date.now() - 12 * 60000),
        level: 'WARN' as const,
        message: 'High memory usage detected: 82%',
        source: 'sys-monitor'
      },
      {
        id: '3',
        timestamp: new Date(Date.now() - 18 * 60000),
        level: 'INFO' as const,
        message: 'Backup completed successfully',
        source: 'backup-service'
      },
      {
        id: '4',
        timestamp: new Date(Date.now() - 25 * 60000),
        level: 'ERROR' as const,
        message: 'Failed to send notification email',
        source: 'email-service'
      },
      {
        id: '5',
        timestamp: new Date(Date.now() - 30 * 60000),
        level: 'WARN' as const,
        message: 'API rate limit approaching threshold',
        source: 'api-gateway'
      },
      {
        id: '6',
        timestamp: new Date(Date.now() - 35 * 60000),
        level: 'INFO' as const,
        message: 'Cache cleared successfully',
        source: 'redis'
      },
      {
        id: '7',
        timestamp: new Date(Date.now() - 40 * 60000),
        level: 'DEBUG' as const,
        message: 'Health check completed for all services',
        source: 'health-monitor'
      }
    ]

    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
        {/* Header */}
        <div>
          <h2 className="text-2xl font-black text-white">System Administration</h2>
          <p className="text-sm text-slate-400 mt-1">Monitoring système et infrastructure</p>
        </div>

        {/* Service Health Indicator */}
        <ServiceHealthIndicator
          services={services}
          onServiceClick={(service) => {
            console.log('View service details:', service.name)
          }}
        />

        {/* System Resources */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <SystemSparkline
            data={cpuData}
            label="CPU Utilisation"
            unit="%"
            threshold={80}
            color="#3b82f6"
          />
          <SystemSparkline
            data={memoryData}
            label="Mémoire"
            unit="%"
            threshold={80}
            color="#8b5cf6"
          />
        </div>

        {/* Operational Status Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-slate-800/20 border-2 border-green-500/30 rounded-2xl p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-black text-slate-300">Statut Global</h3>
              <span className="w-4 h-4 bg-green-500 rounded-full animate-pulse shadow-lg shadow-green-500/50"></span>
            </div>
            <p className="text-3xl font-black text-green-400">OPÉRATIONNEL</p>
            <p className="text-xs text-slate-400 mt-2">✓ Tous systèmes nominaux</p>
            <div className="mt-4 pt-4 border-t border-white/5 space-y-1 text-xs">
              <div className="flex justify-between">
                <span className="text-slate-500">Uptime:</span>
                <span className="text-green-400 font-bold">99.8%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Services actifs:</span>
                <span className="text-green-400 font-bold">{services.filter(s => s.status === 'healthy').length}/{services.length}</span>
              </div>
            </div>
          </div>

          <div className="bg-slate-800/20 border border-blue-500/30 rounded-2xl p-6">
            <h3 className="text-sm font-black text-slate-300 mb-4">Incidents</h3>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-500">Critiques:</span>
                <span className={`text-2xl font-black ${congestionMetrics.critical > 0 ? 'text-red-400' : 'text-green-400'}`}>
                  {congestionMetrics.critical}
                </span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-500">Alertes:</span>
                <span className="text-2xl font-black text-yellow-400">{congestionMetrics.warning}</span>
              </div>
              <div className="text-[10px] text-slate-500 pt-2 border-t border-white/5">Trend: ↓ -8% vs hier</div>
            </div>
          </div>

          <div className="bg-slate-800/20 border border-purple-500/30 rounded-2xl p-6">
            <h3 className="text-sm font-black text-slate-300 mb-4">Métriques</h3>
            <div className="space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-slate-400">Cellules Actives</span>
                <span className="font-bold text-green-400">{stats?.totalCells || 0}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Débit Total</span>
                <span className="font-bold text-blue-400">{metrics?.dataVolume || '0'} Gb/h</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Santé Réseau</span>
                <span className="font-bold text-purple-400">{congestionMetrics.healthScore.toFixed(0)}%</span>
              </div>
            </div>
          </div>
        </div>

        {/* Logs System */}
        {canView(role, 'logsIncidents') && (
        <FilteredLogStream logs={mockLogs} maxItems={15} />
        )}
      </div>
    )
  }

  // NETWORK OPERATOR VIEW - 24/7 Surveillance  
  if (role === 'network_operator') {
    // Generate timeline data from alerts
    const timelineData = alerts?.map(alert => ({
      timestamp: new Date(alert.timestamp),
      count: 1,
      severity: alert.severity
    })) || []

    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
        {/* Full Screen Toggle */}
        <div className="flex justify-end">
          <FullScreenToggle />
        </div>

        {/* Critical Alert Banner with Sound */}
        {congestionMetrics.critical > 0 && (
          <CriticalAlertBanner
            criticalCount={congestionMetrics.critical}
            warningCount={congestionMetrics.warning}
            enableSound={true}
          />
        )}

        {/* Critical Alerts - Large & Prominent */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className={`relative bg-gradient-to-br ${congestionMetrics.critical > 0 ? 'from-red-900/40 to-red-900/10' : 'from-green-900/40 to-green-900/10'} border-2 ${congestionMetrics.critical > 0 ? 'border-red-500/60' : 'border-green-500/60'} rounded-2xl p-6 hover:scale-105 transition-transform`}>
            <div className="absolute top-4 right-4 text-3xl animate-pulse">{congestionMetrics.critical > 0 ? '🚨' : '✅'}</div>
            <p className="text-xs text-slate-400 uppercase font-bold mb-3">Alertes Critiques</p>
            <p className={`text-6xl font-black leading-none ${congestionMetrics.critical > 0 ? 'text-red-500' : 'text-green-500'}`}>{congestionMetrics.critical}</p>
            <div className="mt-4 pt-4 border-t border-white/10">
              {congestionMetrics.critical > 0 && <p className="text-xs text-red-300 animate-pulse font-bold">⚠️ Action requise immédiatement</p>}
              {congestionMetrics.critical === 0 && <p className="text-xs text-green-300 font-bold">✓ Aucune alerte critique</p>}
            </div>
          </div>

          <div className="bg-gradient-to-br from-yellow-900/40 to-yellow-900/10 border-2 border-yellow-500/60 rounded-2xl p-6 hover:scale-105 transition-transform relative">
            <div className="absolute top-4 right-4 text-3xl">⚠️</div>
            <p className="text-xs text-slate-400 uppercase font-bold mb-3">Zones Alertes</p>
            <p className="text-6xl font-black text-yellow-500 leading-none">{congestionMetrics.warning}</p>
            <div className="mt-4 pt-4 border-t border-white/10">
              {congestionMetrics.warning > 0 && <p className="text-xs text-yellow-300 font-bold">📊 À monitorer étroitement</p>}
              {congestionMetrics.warning === 0 && <p className="text-xs text-green-300 font-bold">✓ Zones stables</p>}
            </div>
          </div>

          <div className="bg-gradient-to-br from-green-900/40 to-green-900/10 border-2 border-green-500/60 rounded-2xl p-6 hover:scale-105 transition-transform relative">
            <div className="absolute top-4 right-4 text-3xl">📡</div>
            <p className="text-xs text-slate-400 uppercase font-bold mb-3">Cellules Actives</p>
            <p className="text-6xl font-black text-green-500 leading-none">{stats?.totalCells || 0}</p>
            <div className="mt-4 pt-4 border-t border-white/10">
              <p className="text-xs text-green-300 font-bold">✓ {Math.round((((stats?.totalCells || 0) - congestionMetrics.critical - congestionMetrics.warning) / Math.max(1, stats?.totalCells || 1)) * 100)}% Normales</p>
            </div>
          </div>
        </div>

        {/* Map + Incident Panel */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Live Map (60% width) */}
          <div className="lg:col-span-2 relative bg-slate-900/50 backdrop-blur-sm border border-white/5 rounded-2xl overflow-hidden shadow-xl min-h-[600px]">
            <div className="absolute top-6 left-6 z-10 bg-slate-950/80 backdrop-blur-lg px-4 py-3 rounded-xl border border-white/10">
              <p className="text-xs font-black text-red-400 uppercase animate-pulse">🔴 En direct</p>
              <p className="text-xs text-slate-300 font-bold mt-1">Cliquez sur les cellules pour détails</p>
            </div>
            <CongestionMap
              congestionCells={congestionCells || []}
              warnThreshold={70}
              critThreshold={90}
              className="w-full h-full"
            />
          </div>

          {/* Incident Panel (40% width) */}
          <div>
            <IncidentPanel
              alerts={alerts || []}
              maxItems={8}
              onAssign={(alertId, operator) => {
                console.log(`Alert ${alertId} assigned to ${operator}`)
              }}
              onResolve={(alertId) => {
                console.log(`Alert ${alertId} resolved`)
              }}
            />
          </div>
        </div>

        {/* Timeline 30 minutes */}
        <AlertTimeline
          data={timelineData}
          durationMinutes={30}
        />
      </div>
    )
  }

  // PERFORMANCE ENGINEER VIEW - Analytics & Optimization
  if (role === 'performance_engineer') {
    // Generate mock data for analytics components
    const loadDistributionData = congestionCells?.map(c => c.score) || Array.from({ length: 50 }, () => Math.random() * 100)
    
    const calendarHeatmapData = Array.from({ length: 7 * 24 }, (_, i) => ({
      day: Math.floor(i / 24),
      hour: i % 24,
      value: 30 + Math.random() * 60
    }))
    
    const cellComparisonData = topCells?.slice(0, 12).map(cell => ({
      id: cell.cellId,
      name: `Cell ${cell.cellId}`,
      data: generateMockTimeSeries(24, cell.totalActivity, 10).map(d => d.value),
      current: cell.totalActivity,
      avg: cell.totalActivity * 0.8,
      max: cell.totalActivity * 1.2
    })) || []
    
    const recommendations = [
      {
        id: '1',
        type: 'critical' as const,
        title: `Cellule ${metrics?.peakId} en surcharge`,
        description: `La charge actuelle de ${metrics?.peakValue} Mbps dépasse le seuil critique de 100 Mbps. Risque de dégradation service.`,
        impact: 'Rééquilibrage immédiat peut améliorer les performances de 25%',
        action: 'Appliquer Rééquilibrage',
        priority: 9
      },
      ...(congestionMetrics.critical > 0 ? [{
        id: '2',
        type: 'warning' as const,
        title: 'Zones multiples en état critique',
        description: `${congestionMetrics.critical} cellules dépassent 90% de charge. Surveillance accrue nécessaire.`,
        impact: 'Prévention des pannes potentielles affectant ${congestionMetrics.critical * 1000} utilisateurs',
        action: 'Voir Détails',
        priority: 8
      }] : []),
      {
        id: '3',
        type: 'optimization' as const,
        title: 'Optimisation bande passante disponible',
        description: 'Analyse ML détecte une opportunité de redistribution du trafic vers les zones sous-utilisées.',
        impact: 'Amélioration globale de 15% du débit réseau',
        action: 'Simuler Optimisation',
        priority: 6
      },
      {
        id: '4',
        type: 'info' as const,
        title: 'Pattern de charge hebdomadaire identifié',
        description: 'Les pics se produisent systématiquement entre 18h-20h en semaine.',
        impact: 'Planification proactive de la capacité',
        priority: 4
      }
    ]

    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
        {/* Header with Date Range Picker */}
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-black text-white">Performance Analytics</h2>
            <p className="text-sm text-slate-400 mt-1">Analyse avancée et optimisation réseau</p>
          </div>
          <DateRangePicker
            onChange={(start, end) => {
              console.log('Date range selected:', start, end)
            }}
          />
        </div>

        {/* Load Distribution & Calendar Heatmap */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <LoadDistributionHistogram
            data={loadDistributionData}
            bucketSize={10}
            title="Distribution des Charges"
          />
          <CalendarHeatmap
            data={calendarHeatmapData}
            title="Carte Thermique Temporelle"
          />
        </div>

        {/* Small Multiples - Cell Comparison */}
        <SmallMultiplesChart
          cells={cellComparisonData}
          title="Comparaison Multi-Cellules"
          onCellClick={(cellId) => {
            console.log('Cell clicked:', cellId)
          }}
        />

        {/* Map + Recommendations */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {canView(role, 'interactiveMap') && (
          <div className="lg:col-span-2 relative bg-slate-900/50 backdrop-blur-sm border border-white/5 rounded-2xl overflow-hidden shadow-xl min-h-[500px]">
            <div className="absolute top-4 left-4 z-10">
              <DateRangePicker
                onChange={(start, end) => {
                  console.log('Map date range:', start, end)
                }}
              />
            </div>
            <CongestionMap
              congestionCells={congestionCells || []}
              warnThreshold={70}
              critThreshold={90}
              className="w-full h-full"
            />
          </div>
          )}

          {/* Intelligent Recommendations */}
          {canView(role, 'recommendations') && (
          <div className={`${!canView(role, 'interactiveMap') ? 'lg:col-span-3' : ''}`}>
            <IntelligentRecommendations
              recommendations={recommendations}
              onActionClick={(rec) => {
                console.log('Action clicked:', rec.title)
              }}
            />
          </div>
          )}
        </div>

        {/* Export Options */}
        {canView(role, 'exportReporting') && (
        <div className="bg-slate-800/20 border border-white/5 rounded-2xl p-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-black text-white uppercase">Exporter l'Analyse</h3>
              <p className="text-xs text-slate-400 mt-1">Télécharger les données et visualisations</p>
            </div>
            <ExportButton
              onExport={async (format) => {
                console.log('Exporting as:', format)
                await new Promise(resolve => setTimeout(resolve, 2000))
              }}
            />
          </div>
        </div>
        )}
      </div>
    )
  }

  // OPERATIONS MANAGER VIEW - KPIs & Reporting
  if (role === 'operations_manager') {
    // Generate mock data for executive summary
    const executiveKpis = [
      {
        label: 'Disponibilité Réseau',
        value: 99.8,
        unit: '%',
        target: 99.9,
        trend: Array.from({ length: 7 }, (_, i) => 98 + Math.random() * 2),
        status: 'good' as const,
        change: 0.2,
        icon: '📡'
      },
      {
        label: 'Satisfaction Client',
        value: 96,
        unit: '%',
        target: 95,
        trend: Array.from({ length: 7 }, (_, i) => 94 + Math.random() * 3),
        status: 'good' as const,
        change: 2.5,
        icon: '⭐'
      },
      {
        label: 'MTTR Incidents',
        value: 12,
        unit: 'min',
        target: 15,
        trend: Array.from({ length: 7 }, (_, i) => 15 - i * 0.5 + Math.random() * 2),
        status: 'good' as const,
        change: -15.2,
        icon: '⚡'
      }
    ]

    const insights = [
      {
        id: '1',
        category: 'performance' as const,
        text: `Le réseau affiche une performance exceptionnelle avec un uptime de 99.8% sur les 7 derniers jours, dépassant légèrement l'objectif SLA de 99.9%.`,
        confidence: 0.95,
        dataPoints: ['Uptime: 99.8%', 'Objectif: 99.9%', 'Période: 7j']
      },
      {
        id: '2',
        category: 'trend' as const,
        text: `Tendance positive sur la résolution d'incidents : le MTTR a diminué de 15% pour atteindre 12 minutes, en avance sur l'objectif de 15 minutes.`,
        confidence: 0.89,
        dataPoints: ['MTTR actuel: 12min', 'Cible: 15min', 'Amélioration: -15%']
      },
      {
        id: '3',
        category: 'capacity' as const,
        text: `La capacité réseau est bien dimensionnée avec une charge moyenne de ${metrics?.avgLoad || '0'} Erlang, permettant une marge de manœuvre confortable.`,
        confidence: 0.82,
        dataPoints: [`Charge moy: ${metrics?.avgLoad}E`, `Cellules: ${stats?.totalCells}`, 'Marge: 30%']
      }
    ]

    const slaMetrics = [
      {
        name: 'Disponibilité',
        current: 99.8,
        target: 99.9,
        unit: '%',
        icon: '🎯'
      },
      {
        name: 'Latence',
        current: 15,
        target: 20,
        unit: 'ms',
        icon: '⚡'
      },
      {
        name: 'Débit Min',
        current: 95,
        target: 90,
        unit: 'Mbps',
        icon: '📶'
      },
      {
        name: 'Satisfaction',
        current: 96,
        target: 95,
        unit: '%',
        icon: '⭐'
      }
    ]

    const actionItems = [
      {
        id: '1',
        priority: 'high' as const,
        title: `Optimiser cellule ${metrics?.peakId}`,
        description: `La cellule atteint ${metrics?.peakValue} Mbps, proche de la limite de capacité`,
        assignee: 'Équipe Performance',
        deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        status: 'in-progress' as const,
        category: 'Performance'
      },
      {
        id: '2',
        priority: 'medium' as const,
        title: 'Révision planification capacité Q2',
        description: 'Analyser les tendances de croissance pour anticiper les besoins',
        assignee: 'Manager Réseau',
        deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        status: 'pending' as const,
        category: 'Planification'
      },
      {
        id: '3',
        priority: 'low' as const,
        title: 'Documentation mise à jour KPIs',
        description: 'Mettre à jour les seuils d\'alerte dans la documentation',
        assignee: 'Équipe Qualité',
        deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        status: 'pending' as const,
        category: 'Documentation'
      }
    ]

    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
        {/* Header with Period Comparator & Export */}
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-black text-white">Rapport Opérations</h2>
            <p className="text-sm text-slate-400 mt-1">Vue exécutive et reporting</p>
          </div>
          <div className="flex items-center gap-4">
            <PeriodComparator
              onChange={(current, comparison) => {
                console.log('Comparing periods:', current, comparison)
              }}
            />
            {canView(role, 'exportReporting') && (
            <ExportButton
              onExport={async (format) => {
                console.log('Exporting report as:', format)
                await new Promise(resolve => setTimeout(resolve, 2000))
              }}
            />
            )}
          </div>
        </div>

        {/* Executive Summary Cards */}
        {canView(role, 'kpiCards') && (
        <ExecutiveSummaryCards kpis={executiveKpis} />
        )}

        {/* SLA Gauges */}
        <SlaGauges metrics={slaMetrics} />

        {/* Insights & Map */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Auto-Generated Insights */}
          <div className="lg:col-span-1">
            <AutoGeneratedInsights insights={insights} />
          </div>

          {/* Map */}
          {canView(role, 'interactiveMap') && (
          <div className="lg:col-span-2 relative bg-slate-900/50 backdrop-blur-sm border border-white/5 rounded-2xl overflow-hidden shadow-xl min-h-[500px]">
            <CongestionMap
              congestionCells={congestionCells || []}
              warnThreshold={70}
              critThreshold={90}
              className="w-full h-full"
            />
          </div>
          )}
        </div>

        {/* Action Items */}
        <ActionItems
          items={actionItems}
          onStatusChange={(id, status) => {
            console.log(`Action ${id} status changed to ${status}`)
          }}
        />

        {/* Trends Visualization */}
        {canView(role, 'timeseries') && (
        <div className="bg-slate-800/20 border border-white/5 rounded-2xl p-6">
          <h3 className="text-sm font-black text-white uppercase mb-4">Tendances (7 derniers jours)</h3>
          <div className="grid grid-cols-7 gap-2">
            {['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'].map((day, idx) => {
              const height = 50 + Math.random() * 50;
              const value = 60 + Math.floor(Math.random() * 30);
              return (
                <div key={day} className="flex flex-col items-center">
                  <div className="text-xs text-slate-400 font-bold mb-2">{day}</div>
                  <div className="relative h-32 w-full bg-slate-900 rounded-lg flex items-end justify-center p-2 group hover:bg-slate-800/50 transition-all cursor-pointer">
                    <div className="flex items-end gap-0.5 h-full w-full justify-center">
                      <div
                        className="flex-1 bg-gradient-to-t from-blue-600 to-blue-400 rounded-t-md shadow-lg shadow-blue-500/30 hover:shadow-xl hover:from-blue-500 transition-all"
                        style={{height: `${height}%`}}
                        title={`${value}% santé réseau`}
                      ></div>
                    </div>
                    <div className="absolute bottom-full mb-2 opacity-0 group-hover:opacity-100 transition-opacity bg-slate-950 border border-white/10 px-2 py-1 rounded text-[10px] text-slate-300 whitespace-nowrap z-10">
                      {value}% santé
                    </div>
                  </div>
                  <div className="text-xs font-bold text-blue-400 mt-2">{value}%</div>
                </div>
              );
            })}
          </div>
          <div className="mt-4 pt-4 border-t border-white/5">
            <p className="text-[10px] text-slate-500">📊 Moy: 82% • Pic: 95% • Min: 58%</p>
          </div>
        </div>
        )}
      </div>
    )
  }

  // Default fallback
  return (
    <div className="text-center py-20">
      <p className="text-slate-400">Dashboard non disponible</p>
    </div>
  )
}
